version: '3.7'

services:
  persons-mongo:
    container_name: persons-mongo
    image: mongo:4.0.7-xenial
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      - MONGO_INITDB_DATABASE=persons
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - /tmp/owl/persons-mongo:/data/db
      - /tmp/owl/persons-mongo/config:/data/configdb
    restart: on-failure

  access-roles-postgresql:
    container_name: access-roles-postgresql
    image: postgres:12
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=access_roles
    ports:
      - 5432:5432
    volumes:
      - /tmp/owl/access-roles-postgresql:/var/lib/postgresql/data
    restart: on-failure

  cards-mongo:
    container_name: cards-mongo
    image: mongo:4.0.7-xenial
    ports:
      - 27018:27017
    expose:
      - 27018
    environment:
      - MONGO_INITDB_DATABASE=cards
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - /tmp/owl/cards-mongo:/data/db
      - /tmp/owl/cards-mongo/config:/data/configdb
    restart: on-failure

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /tmp/owl/kafka/docker.sock:/var/run/docker.sock