version: '3.7'

services:
  service-discovery:
    container_name: service-discovery
    hostname: service-discovery
    build:
      context: .
      dockerfile: Dockerfile.eureka
    ports:
      - 8761:8761
    expose:
      - 8761
    volumes:
      - /tmp/access-roles/service-discovery
    restart: on-failure

  persons-mongo:
    container_name: persons-mongo
    image: mongo:4.0.7-xenial
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      - MONGO_INITDB_DATABASE=persons
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - /tmp/access-roles/persons-mongo
    restart: on-failure

  persons-app:
    container_name: persons-app
    build:
      context: .
      dockerfile: Dockerfile.persons
    ports:
      - 8090:8090
    depends_on:
      - service-discovery
      - persons-mongo
    environment:
      - DATABASE_HOST=persons-mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=persons
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
    volumes:
      - /tmp/access-roles/persons
    restart: on-failure
    links:
      - service-discovery

  access-roles-mysql:
    container_name: access-roles-mysql
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: access_roles
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: mysecret
    volumes:
      - /tmp/access-roles/access-roles-mysql:/var/lib/mysql
    restart: on-failure

  access-roles-app:
    container_name: access-roles-app
    build:
      context: .
      dockerfile: Dockerfile.access-roles
    ports:
      - 8080:8080
    depends_on:
      - service-discovery
      - access-roles-mysql
    environment:
      - DATABASE_HOST=access-roles-mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=access_roles
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
    volumes:
      - /tmp/access-roles//access-roles-app
    restart: on-failure
    links:
      - service-discovery