spring:
  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/persons?authSource=admin&authMechanism=SCRAM-SHA-1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka