server:
  port: 8080

spring:
  application:
    name: gateway-api

zuul:
  ignoredServices: '*'
  routes:
    access-roles-app:
      path: /access-roles/**
      serviceId: access-roles-app
      stripPrefix: false
    locations-app:
      path: /locations/**
      serviceId: access-roles-app
      stripPrefix: false
    persons-app:
      path: /persons/**
      serviceId: persons-app
      stripPrefix: false
    cards-app:
      path: /cards/**
      serviceId: cards-app
      stripPrefix: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka
    fetchRegistry: true