server:
  port: 8080

spring:
  application:
    name: gateway-api
  datasource:
    url: jdbc:h2:mem:default
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
  h2:
    console:
      enabled: true

zuul:
  ignoredServices: '*'
  routes:
    access-roles-app:
      path: /access-roles/**
      serviceId: access-roles-app
      stripPrefix: false
    locations-app:
      path: /locations/**
      serviceId: access-roles-app
      stripPrefix: false
    persons-app:
      path: /persons/**
      serviceId: persons-app
      stripPrefix: false
    cards-app:
      path: /cards/**
      serviceId: cards-app
      stripPrefix: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka
    fetchRegistry: true