server:
  port: 8080

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: access-roles-app
          uri: lb://access-roles-app
          predicates:
            - Path=/access-roles/**
          filters:
            - RewritePath=/access-roles/(?<path>.*), /$\{path}
        - id: locations-app
          uri: lb://access-roles-app
          predicates:
            - Path=/locations/**
          filters:
            - RewritePath=/locations/(?<path>.*), /$\{path}
        - id: persons-app
          uri: lb://persons-app
          predicates:
            - Path=/persons/**
          filters:
            - RewritePath=/persons/(?<path>.*), /$\{path}
        - id: cards-app
          uri: lb://cards-app
          predicates:
            - Path=/cards/**
          filters:
            - RewritePath=/cards/(?<path>.*), /$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka
    fetchRegistry: true