server:
  port: 8761

spring:
  application:
    name: service-discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging.level.org.springframework.boot.autoconfigure: ERROR