spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/access_roles
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka