server:
  port: 8091

spring:
  profiles:
    active: dev
  application:
    name: cards-app
  jackson:
    default-property-inclusion: non_null
  datasource:
    initialization-mode: always
  kafka:
    consumer:
      group-id: cards-app
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.github.nl4.owl.common.messaging

app:
  topic:
    access-role: access-role
    location: location
    person: person

eureka:
  client:
    fetchRegistry: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging.level.org.apache.kafka.clients: ERROR
logging.level.org.apache.kafka.common.utils: ERROR
logging.level.org.springframework.boot.autoconfigure: ERROR