db_parameters: authSource=admin&authMechanism=SCRAM-SHA-1

server:
  port: 8091

spring:
  application:
    name: cards-app
  jackson:
    default-property-inclusion: non_null
  data:
    mongodb:
      uri: mongodb://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?${db_parameters}
  datasource:
    initialization-mode: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka
    fetchRegistry: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging.level.com.github.nl4.accessroles.client.AccessRolesClient: DEBUG
